### ISSUE TITLE
Is this going to registered to crate.io?

### ISSUE THREAD

**Issue by Ameyanagi** [mitric-lab/Rusty-FITPACK#2]
Thank you for creating a very nice crate.
Are you thinking of registering to crate.io?

I would really appreciate it if you do so.

**Comment by hochej** [comment]
Sure, I'm happy to do that. I'll take care of it right away and close the issue as soon as it's done. Thanks for the feedback.

**Comment by hochej** [comment]
https://crates.io/crates/rusty-fitpack

If there are any problems, please re-open the issue.
